### PR TITLE
Add PHP 8.2 Support

### PR DESCRIPTION
**Pull request by patinthehat**
This PR adds PHP 8.2 to the tests workflow and bumps the checkout action version to v3.

It also bumps the minimum required version of `nesbot/carbon` to enable PHP 8.2 support.

### CODE REVIEW

**Comment by patinthehat** [comment]
@freekmurze Once #278 is merged, all tests should pass.

**Comment by freekmurze** [comment]
I reran the tests, but they still seem to be failing.

**Comment by patinthehat** [comment]
@freekmurze just needed to rebase first :) all tests are passing now!

**Comment by freekmurze** [comment]
Very nice, thanks!

**Pull request merged**
