### PR TITLE
Try catch `DB::enableQueryLog` to Handle Cases when connection is not setup.

### PR DESCRIPTION
**Pull request by bogdankharchenko**
Problem: Vapor injects DB_* -- when deploying to Vapor, DB_* is not set from .env pull thus this fails during composer autoload.

### CODE REVIEW

**Comment by freekmurze** [comment]
The tests are failing for this one, could you take a look at that?

**Comment by bogdankharchenko** [comment]
> The tests are failing for this one, could you take a look at that?

Looking at it today -- didn't know have time yesterday!

**Comment by bogdankharchenko** [comment]
@freekmurze so I took another stab at it

and the real issue is that -- the db connection is just not properly setup during composer install.

Steps to reproduce:  
Install Fresh Laravel + Laravel-Ray without having a "forge" database as specified.  And this will fail during composer autoload.

So I figured, perhaps we just check if we even have a connection in the first place, rather than looking at the config.  Seems to be a solution, but I'll be interested to know a better approach from your angle. 

Thanks!

**Comment by freekmurze** [comment]
This PR is marked as draft. et me know when it is ready to be reviewed.

**Comment by bogdankharchenko** [comment]
@freekmurze I removed the draft -- go ahead and take a look

**Pull request closed without merging**
