### PR TITLE
Add conditional query watcher and convenience methods for update, delete, insert and select queries

### PR DESCRIPTION
**Pull request by patrickomeara**
When I'm writing migrations or commands that change a lot of data I often want to see just the write queries, or just the updates or deletes, depending on what the context is. But the queries I want to see are usually amongst 10s to 100s times as many queries that I don't want to see. The execution slows down and Ray struggles to then filter through so many payloads.

This PR allows the user to conditionally send queries based on the query itself, no longer bogging down Ray or littering the UI with pointless queries.

Additionally I have added convenience methods around insert, select, update and delete queries, all of which can be turned on in the config.

`SlowQueryWatcher` is a great example of what `ConditionalQueryWatcher` can be used for.

### CODE REVIEW

**Comment by freekmurze** [comment]
Very nice!

Could you also send a PR to our docs (which can be found here: https://github.com/spatie/myray.app/tree/main/docs/php/laravel)

**Comment by patrickomeara** [comment]
Looks like I don't have access to that repo @freekmurze. Seem like the improve this page links on https://myray.app/docs/getting-started/introduction are broken as well.

image

**Comment by patrickomeara** [comment]
Just checking in here @freekmurze, I'm happy to write the docs up when possible.

**Comment by freekmurze** [comment]
Could you add docs for this too? Thanks!

**Comment by patrickomeara** [comment]
I don't have access to the docs repo you shared @freekmurze, is it available elsewhere?

**Comment by patrickomeara** [comment]
Circling back on this @freekmurze, I don't have access to the docs repo you provided. I'm happy to provide docs when possible.

**Comment by patrickomeara** [comment]
This has been rebased, still awaiting permissions to add docs. ❤️

**Comment by freekmurze** [comment]
Sorry for the long wait time. You'll find the docs here: https://github.com/spatie/myray.app/tree/main/docs

**Comment by patrickomeara** [comment]
@freekmurze Added in spatie/myray.app#28

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
