### PR TITLE
Add support for Lumen

### PR DESCRIPTION
**Pull request by chris-doehring**
Related to #8, this pull request adds support for Lumen.

### CODE REVIEW

**Comment by chris-doehring** [comment]
There are also two things I have noticed in the [configuration documentation](https://spatie.be/docs/ray/v1/getting-started/configuring-ray):
* The first array is missing a `;` at the end
* The host of the Laravel configuration should not contain `http://` as this is being added by the Client class

**Comment by freekmurze** [comment]
> The first array is missing a ; at the end

I seem to be unable to see that 🙂 Could you send a PR to fix that. You can use the edit button on top of the page.

**Comment by chris-doehring** [comment]
> > The first array is missing a ; at the end
> 
> I seem to be unable to see that 🙂 Could you send a PR to fix that. You can use the edit button on top of the page.

Oh, and I haven't seen that edit button :D Will do that!

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
