### PR TITLE
Add artisan command to create ray.php config file in root

### PR DESCRIPTION
**Pull request by colinhall17**
As per tweet with Freek, this will create the vendor:publish command to create the default ray.php file in the root of the app.

### CODE REVIEW

**Comment by freekmurze** [comment]
I think it would be better to publish the file in the base path of the project (as this configuration is developer specific (and not project specific). The stub should be in a stub directory in this package (otherwise it would be confused with a real config file).

Could you also update the docs at https://github.com/spatie/ray/docs to explain how people can publish this?

Thanks!

**Comment by colinhall17** [comment]
Hi @freekmurze 

It does publish to the base_path

__DIR__.'/../config/ray.php' => base_path('ray.php')

Will change to a stub directory, would you prefer a command over the vendor:publish?

**Comment by freekmurze** [comment]
> It does publish to the base_path

Ah, didn't catch that, thanks!

> Will change to a stub directory,

👍 

> Would you prefer a command over the vendor:publish?

Yes, that would be better! 👍

**Comment by colinhall17** [comment]
@freekmurze 

I have changed to a command and added a couple of helper options

So if you ray:publish-config --homestead or ray:publish-config --docker it will change the host

If you are happy with everything then I will update the docs.

**Comment by freekmurze** [comment]
Awesome work! Thank you so much. Please send a PR to the docs 👍

**Comment by colinhall17** [comment]
@Freek 

PR sent to docs also

**Comment by freekmurze** [comment]
Thank you!

**Pull request merged**
