### PR TITLE
Added Windows path check

### LINKED ISSUE #3: Ray doesn't show file that executed ray helper
Windows 10, IIS

Laravel v8.21.0

Controller:
```
class MyController extends Controller
{
    ...
    public function index()
    {
        ray()->showQueries();

        ray('Hello world');

        return $this->repository->allCarWashes();
    }
    ...
}
```

image

### LINKED ISSUE #11: Ray doesn't show the proper file where ray() was called.
I have added ray('my test') to my index.php file, but it's showing "helpers.php:21" from the ray package as file where it was called.

The same happens if I call `ray('my test from ' . __CLASS__ );` from several different files.
Bildschirmfoto 2021-01-07 um 18 13 42

My environment: OSX with MAMP Pro 5.7

### PR DESCRIPTION
**Pull request by GraxMonzo**
fix #11 
fix #3

### CODE REVIEW

**Comment by GraxMonzo** [comment]
#3 fix

**Comment by bullenb** [comment]
@GraxMonzo I wonder should the new backslash paths use escaped backslashes instead?

For example:
` if ($originFrame && Str::endsWith($originFrame->file, ['ray/src/helpers.php', 'ray\\src\\helpers.php'])) {`

**Comment by GraxMonzo** [comment]
@bullenb In single quoted strings \ is interpreted as a plain character

**Comment by SamuelNitsche** [comment]
I think it is cleaner to use the `DIRECTORY_SEPARATOR` constant.

**Comment by freekmurze** [comment]
I've just added this to `Ray` which you can make use of (will tag a version as soon as I can get passing tests on that package).

https://github.com/spatie/ray/blob/17a2d4e53b0214666cdd32dd5b306d51d17eae2b/src/Ray.php#L332-L335

**Comment by GraxMonzo** [comment]
@freekmurze Done

**Pull request closed without merging**
