### PR TITLE
Fixes open in editor path when used in vagrant, docker and others containers

### LINKED ISSUE #13: Using Ray with Docker can't open files
I realize this is new but great work! I am running a Docker container and have Ray setup and working. However, my path in the container is `/app/public` and the Ray app defaults to the path from the container, not the host machine which makes sense.

Perhaps a config option to set the "file path/root" to the project would resolve this issue?

Screen Shot 2021-01-07 at 12 14 23 PM

Screen Shot 2021-01-07 at 12 15 59 PM

### PR DESCRIPTION
**Pull request by SRWieZ**
Fixes #13

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks!

Could you also open a similar PR at spatie/ray (and also update the docs there with an example on how to use this). I'll take care of tests.

**Comment by freekmurze** [comment]
Thank you!

**Comment by SRWieZ** [comment]
After digging deeper in https://github.com/spatie/ray I learned a bit more on how it works.
I think we should revert this, I should do it better.

**Comment by SRWieZ** [comment]
The approach in https://github.com/spatie/ray/pull/23 one is much better. We should follow that.

**Comment by freekmurze** [comment]
I have modified this PR so it used the changes your made in spatie/ray.

**Pull request merged**
